--------------------------------
-- VENDAS LIQUIDA POR GERENTE --
--------------------------------
CREATE TABLE FONTES.BI0001 (
	CODIGO		  NUMBER(8)     NOT NULL,
	DATA		    DATE          NOT NULL,
	GERENTE		  NUMBER(2)     NOT NULL,
	FAMILIA		  VARCHAR2(2)   NOT NULL,
	QUANTIDADE	NUMBER(10,2)  NOT NULL,
	VALOR		    NUMBER(10,2)  NOT NULL,
	CONSTRAINT BI0001_INDEX01 PRIMARY KEY (CODIGO)
	USING INDEX TABLESPACE TB_INDICES_BI
) TABLESPACE TB_DADOS_BI;
CREATE UNIQUE INDEX BI0001_INDEX02 ON BI0001 (DATA,GERENTE,FAMILIA) TABLESPACE TB_INDICES_BI;
CREATE SEQUENCE BI0001_CODIGO MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 CACHE 5;

--------------
-- GERENTES --
--------------
CREATE TABLE FONTES.BI0002 (
	CODIGO		  NUMBER(2)       NOT NULL,
	NOME		    VARCHAR2(30)    NOT NULL,
	GERENCIA	  NUMBER(2)       NOT NULL,
	INICIO		  DATE            NOT NULL,
	FIM		      DATE,
	CONSTRAINT BI0002_INDEX01 PRIMARY KEY (CODIGO)
	USING INDEX TABLESPACE TB_INDICES_BI
) TABLESPACE TB_DADOS_BI;

---------------
-- GERENCIAS --
---------------
CREATE TABLE FONTES.BI0003 (
	CODIGO		      NUMBER(2)       NOT NULL,
	NOME		        VARCHAR2(40)    NOT NULL,
	GRUPO		        NUMBER(2)       NOT NULL,
  CENTRO_CUSTO		VARCHAR2(8),
	INICIO		      DATE            NOT NULL,
	FIM		          DATE,
  EXIBE		        VARCHAR2(2),
	CONSTRAINT BI0003_INDEX01 PRIMARY KEY (CODIGO)
	USING INDEX TABLESPACE TB_INDICES_BI
) TABLESPACE TB_DADOS_BI;
CREATE UNIQUE INDEX BI0003_INDEX02 ON BI0003 (NOME) TABLESPACE TB_INDICES_BI;

-----------------------
-- GERENCIA - GRUPOS --
-----------------------
CREATE TABLE FONTES.BI0004 (
	CODIGO		  NUMBER(2)     NOT NULL,
	DESCRICAO	  VARCHAR2(30)  NOT NULL,
	CONSTRAINT BI0004_INDEX01 PRIMARY KEY (CODIGO)
	USING INDEX TABLESPACE TB_INDICES_BI
) TABLESPACE TB_DADOS_BI;
CREATE UNIQUE INDEX BI0004_INDEX02 ON BI0004 (DESCRICAO) TABLESPACE TB_INDICES_BI;

INSERT INTO BI0004 VALUES (1,'REVENDA');
INSERT INTO BI0004 VALUES (2,'INTERCOMPANY');
INSERT INTO BI0004 VALUES (3,'OUTRAS');
INSERT INTO BI0004 VALUES (4,'TRANSPORTATION COATINGS');

--------------------------------------------
-- VENDAS LIQUIDA POR SEGMENTO DE MERCADO --
--------------------------------------------
CREATE TABLE FONTES.BI0005 (
	CODIGO		  NUMBER(8)     NOT NULL,
	DATA		    DATE          NOT NULL,
	MERCADO		  NUMBER(2)     NOT NULL,
	FAMILIA		  VARCHAR2(2)   NOT NULL,
	QUANTIDADE	NUMBER(10,2)  NOT NULL,
	VALOR		NUMBER(10,2)      NOT NULL,
	CONSTRAINT BI0005_INDEX01 PRIMARY KEY (CODIGO)
	USING INDEX TABLESPACE TB_INDICES_BI
) TABLESPACE TB_DADOS_BI;
CREATE UNIQUE INDEX BI0005_INDEX02 ON BI0005 (DATA,MERCADO,FAMILIA) TABLESPACE TB_INDICES_BI;
CREATE SEQUENCE BI0005_CODIGO MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 CACHE 5;

-------------------------------
-- MERCADO DE VENDAS LIQUIDA --
-------------------------------
CREATE TABLE FONTES.BI0006 (
	CODIGO		    NUMBER(2)     NOT NULL,
	DESCRICAO	    VARCHAR2(30)  NOT NULL,
	CONSTRAINT BI0006_INDEX01 PRIMARY KEY (CODIGO)
	USING INDEX TABLESPACE TB_INDICES_BI
) TABLESPACE TB_DADOS_BI;

INSERT INTO BI0006 VALUES (1,'Automotiva Brasil');
INSERT INTO BI0006 VALUES (2,'Exportação');
INSERT INTO BI0006 VALUES (3,'Indústria');
INSERT INTO BI0006 VALUES (4,'Intercompany');

-------------------------
-- CUT-OFF POR GERENTE --
-------------------------
CREATE TABLE FONTES.BI0007 (
	CODIGO		  NUMBER(8)     NOT NULL,
	DATA		    DATE          NOT NULL,
	GERENTE		  NUMBER(2)     NOT NULL,
	FAMILIA		  VARCHAR2(2)   NOT NULL,
	QUANTIDADE	NUMBER(10,2)  NOT NULL,
	VALOR		    NUMBER(10,2)  NOT NULL,
	CONSTRAINT BI0007_INDEX01 PRIMARY KEY (CODIGO)
	USING INDEX TABLESPACE TB_INDICES_BI
) TABLESPACE TB_DADOS_BI;
CREATE UNIQUE INDEX BI0007_INDEX02 ON BI0007 (DATA,GERENTE,FAMILIA) TABLESPACE TB_INDICES_BI;
CREATE SEQUENCE BI0007_CODIGO MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 CACHE 5;

-------------------------
-- ACESSO POR PROGRAMA --
-------------------------
CREATE TABLE FONTES.BI0008 (
	CODIGO		NUMBER(6) NOT NULL,
	PROGRAMA	NUMBER(6) NOT NULL,
	USUARIO		NUMBER(4) NOT NULL,
	PERMISSAO	NUMBER(2) NOT NULL,
	CONSTRAINT BI0008_INDEX01 PRIMARY KEY (CODIGO)
	USING INDEX TABLESPACE TB_INDICES_BI
) TABLESPACE TB_DADOS_BI;
CREATE SEQUENCE BI0008_CODIGO MINVALUE 1 MAXVALUE 99 INCREMENT BY 1 CACHE 5;
CREATE UNIQUE INDEX BI0008_INDEX02 ON BI0008 (PROGRAMA,USUARIO) TABLESPACE TB_INDICES_BI;
CREATE INDEX BI0008_INDEX03 ON BI0008 (USUARIO) TABLESPACE TB_INDICES_BI;

---------------
-- PERMISSAO --
---------------
CREATE TABLE FONTES.BI0009 (
	CODIGO		  NUMBER(2)     NOT NULL,
	DESCRICAO	  VARCHAR2(30)          ,
	CONSTRAINT BI0009_INDEX01 PRIMARY KEY (CODIGO)
	USING INDEX TABLESPACE TB_INDICES_BI
) TABLESPACE TB_DADOS_BI;
CREATE SEQUENCE BI0009_CODIGO MINVALUE 1 MAXVALUE 99 INCREMENT BY 1 CACHE 5;

INSERT INTO BI0009 VALUES (BI0009_CODIGO.NEXTVAL,'LEITURA');
INSERT INTO BI0009 VALUES (BI0009_CODIGO.NEXTVAL,'GRAVA��O');

--------------------------------------
-- VENDAS LIQUIDA POR REPRESENTANTE --
--------------------------------------
CREATE TABLE FONTES.BI0010 (
	CODIGO		      NUMBER(10)    NOT NULL,
	DATA		        DATE          NOT NULL,
	REPRESENTANTE	  NUMBER(3)     NOT NULL,
	FAMILIA		      VARCHAR2(2)   NOT NULL,
	QUANTIDADE	    NUMBER(10,2)  NOT NULL,
	VALOR		        NUMBER(10,2)  NOT NULL,
	CONSTRAINT BI0010_INDEX01 PRIMARY KEY (CODIGO)
	USING INDEX TABLESPACE TB_INDICES_BI
) TABLESPACE TB_DADOS_BI;
CREATE SEQUENCE BI0010_CODIGO MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 CACHE 20;

--------------------
-- REPRESENTANTES --
--------------------
CREATE TABLE FONTES.BI0011 (
	CODIGO		NUMBER(3)     NOT NULL,
	NOME		  VARCHAR2(30)  NOT NULL,
	GERENTE		NUMBER(2)     NOT NULL,
	INICIO		DATE          NOT NULL,
	FIM		    DATE                  ,
	CONSTRAINT BI0011_INDEX01 PRIMARY KEY (CODIGO)
	USING INDEX TABLESPACE TB_INDICES_BI
) TABLESPACE TB_DADOS_BI;

-------------------------------
-- CUT-OFF POR REPRESENTANTE --
-------------------------------
CREATE TABLE FONTES.BI0012 (
	CODIGO		      NUMBER(8)     NOT NULL,
	DATA		        DATE          NOT NULL,
	REPRESENTANTE   NUMBER(3)     NOT NULL,
	FAMILIA		      VARCHAR2(2)   NOT NULL,
	QUANTIDADE	    NUMBER(10,2)  NOT NULL,
	VALOR		        NUMBER(10,2)  NOT NULL,
	CONSTRAINT BI0012_INDEX01 PRIMARY KEY (CODIGO)
	USING INDEX TABLESPACE TB_INDICES_BI
) TABLESPACE TB_DADOS_BI;
CREATE UNIQUE INDEX BI0012_INDEX02 ON BI0012 (DATA,REPRESENTANTE,FAMILIA) TABLESPACE TB_INDICES_BI;
CREATE SEQUENCE BI0012_CODIGO MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 CACHE 20;

--------------------
-- GRUPOS DE CLIENTES --
--------------------
CREATE TABLE FONTES.BI0014 (
	CODIGO		    NUMBER(6)     NOT NULL,
	DESCRICAO	  	VARCHAR2(80)  NOT NULL,
	CONSTRAINT BI0014_INDEX01 PRIMARY KEY (CODIGO)
	USING INDEX TABLESPACE TB_INDICES_BI
) TABLESPACE TB_DADOS_BI;
CREATE SEQUENCE BI0014_CODIGO MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 CACHE 3;

--------------------
-- CLIENTES --
--------------------
CREATE TABLE FONTES.BI0013 (
	CODIGO		              NUMBER(11)    NOT NULL,
	NOME	  	              VARCHAR2(80)  NOT NULL,
  GRUPO		                NUMBER(8)     NOT NULL,
  SETOR                   NUMBER(4)     NOT NULL,
  SETOR2                  NUMBER(4)             ,
	INICIO		              DATE          NOT NULL,
	FIM		                  DATE                  ,
  STATUS_CANCELAMENTO	  	VARCHAR2(2)   NOT NULL,
	CONSTRAINT BI0013_INDEX01 PRIMARY KEY (CODIGO)
	USING INDEX TABLESPACE TB_INDICES_BI
) TABLESPACE TB_DADOS_BI;
CREATE SEQUENCE BI0013_CODIGO MINVALUE 1 MAXVALUE 99999999999 INCREMENT BY 1 CACHE 3;

--------------------
-- PRODUTOS --
--------------------
CREATE TABLE FONTES.BI0033 (
	CODIGO		                 NUMBER(11)    NOT NULL,
	GRUPO	  	                 VARCHAR2(3)   NOT NULL,
	SUBGRUPO                   VARCHAR2(3)   NOT NULL,
  NUMERO		                 VARCHAR2(6)   NOT NULL,
  UNIDADE                    VARCHAR2(4)   NOT NULL,
  AGRUPAMENTO                VARCHAR2(3)           ,
  SUBAGRUPAMENTO             VARCHAR2(4)           ,
  ABREVIACAO                 VARCHAR2(6)   NOT NULL,
  DESCRICAO                  VARCHAR2(50)  NOT NULL,
  STATUS_CANCELAMENTO        VARCHAR2(2)           ,
  DATA_CANCELAMENTO          DATE                  ,
	CONSTRAINT BI0033_INDEX01 PRIMARY KEY (CODIGO)
	USING INDEX TABLESPACE TB_INDICES_BI
) TABLESPACE TB_DADOS_BI;
CREATE SEQUENCE BI0033_CODIGO MINVALUE 1 MAXVALUE 99999999999 INCREMENT BY 1 CACHE 3;

--------------------
-- PRODUTOS AGRUPAMENTOS --
--------------------
CREATE TABLE FONTES.BI0034 (
	CODIGO		        NUMBER(11)    NOT NULL,
	AGRUPAMENTO       VARCHAR2(3)   NOT NULL,
	SUBAGRUPAMENTO    VARCHAR2(3)   NOT NULL,
  FAMILIA		        VARCHAR2(6)   NOT NULL,
  SUBFAMILIA        VARCHAR2(4)   NOT NULL,
	CONSTRAINT BI0034_INDEX01 PRIMARY KEY (CODIGO)
	USING INDEX TABLESPACE TB_INDICES_BI
) TABLESPACE TB_DADOS_BI;
CREATE SEQUENCE BI0034_CODIGO MINVALUE 1 MAXVALUE 99999999999 INCREMENT BY 1 CACHE 3;

--------------------
-- FAMILIA POLITICA --
--------------------
CREATE TABLE FONTES.BI0035 (
	CODIGO		            NUMBER(11)    NOT NULL,
	FAMILIA               VARCHAR2(3)   NOT NULL,
	DESCRICAO             VARCHAR2(20)          ,
  SEQUENCIA_EXIBICAO		NUMBER(2,0)   NOT NULL,
	CONSTRAINT BI0035_INDEX01 PRIMARY KEY (CODIGO)
	USING INDEX TABLESPACE TB_INDICES_BI
) TABLESPACE TB_DADOS_BI;
CREATE SEQUENCE BI0035_CODIGO MINVALUE 1 MAXVALUE 99999999999 INCREMENT BY 1 CACHE 3;

--------------------
-- NOME SUBFAMILIA --
--------------------
CREATE TABLE FONTES.BI0036 (
	CODIGO		            NUMBER(11)    NOT NULL,
	SUBFAMILIA            VARCHAR2(6)   NOT NULL,
	DESCRICAO             VARCHAR2(40)          ,
	CONSTRAINT BI0036_INDEX01 PRIMARY KEY (CODIGO)
	USING INDEX TABLESPACE TB_INDICES_BI
) TABLESPACE TB_DADOS_BI;
CREATE SEQUENCE BI0036_CODIGO MINVALUE 1 MAXVALUE 99999999999 INCREMENT BY 1 CACHE 3;

--------------------
-- NOME AGRUPAMENTO --
--------------------
CREATE TABLE FONTES.BI0037 (
	CODIGO		            NUMBER(11)    NOT NULL,
	AGRUPAMENTO           VARCHAR2(4)   NOT NULL,
	DESCRICAO             VARCHAR2(40)          ,
	CONSTRAINT BI0037_INDEX01 PRIMARY KEY (CODIGO)
	USING INDEX TABLESPACE TB_INDICES_BI
) TABLESPACE TB_DADOS_BI;
CREATE SEQUENCE BI0037_CODIGO MINVALUE 1 MAXVALUE 99999999999 INCREMENT BY 1 CACHE 3;

--------------------
-- NOME SUBAGRUPAMENTO --
--------------------
CREATE TABLE FONTES.BI0038 (
	CODIGO		            NUMBER(11)    NOT NULL,
	SUBAGRUPAMENTO        VARCHAR2(4)   NOT NULL,
	DESCRICAO             VARCHAR2(40)          ,
	CONSTRAINT BI0038_INDEX01 PRIMARY KEY (CODIGO)
	USING INDEX TABLESPACE TB_INDICES_BI
) TABLESPACE TB_DADOS_BI;
CREATE SEQUENCE BI0038_CODIGO MINVALUE 1 MAXVALUE 99999999999 INCREMENT BY 1 CACHE 3;

-----------------
-- CONSTRAINTS --
-----------------
ALTER TABLE FONTES.BI0001
	ADD CONSTRAINT REL_BI0001_BI0002
	FOREIGN KEY (GERENTE)
	REFERENCES FONTES.BI0002(CODIGO);

ALTER TABLE FONTES.BI0002
	ADD CONSTRAINT REL_BI0002_BI0003
	FOREIGN KEY (GERENCIA)
	REFERENCES FONTES.BI0003(CODIGO);

ALTER TABLE FONTES.BI0003
	ADD CONSTRAINT REL_BI0003_BI0004
	FOREIGN KEY (GRUPO)
	REFERENCES FONTES.BI0004(CODIGO);

ALTER TABLE FONTES.BI0005
	ADD CONSTRAINT REL_BI0005_BI0006
	FOREIGN KEY (MERCADO)
	REFERENCES FONTES.BI0006(CODIGO);

ALTER TABLE FONTES.BI0008
	ADD CONSTRAINT REL_BI0008_BI0009
	FOREIGN KEY (PERMISSAO)
	REFERENCES FONTES.BI0009(CODIGO);

ALTER TABLE FONTES.BI0010
	ADD CONSTRAINT REL_BI0010_BI0011
	FOREIGN KEY (REPRESENTANTE)
	REFERENCES FONTES.BI0011(CODIGO);

ALTER TABLE FONTES.BI0011
	ADD CONSTRAINT REL_BI0011_BI0002
	FOREIGN KEY (GERENTE)
	REFERENCES FONTES.BI0002(CODIGO);

COMMIT;



