ALTER SESSION SET PLSQL_WARNINGS='ENABLE:ALL';

CREATE OR REPLACE PACKAGE MY_PACKAGE IS
  TYPE string_tabtype IS TABLE OF VARCHAR2(20)
    INDEX BY BINARY_INTEGER;
  PROCEDURE process_text(strtab IN OUT string_tabtype);
END;
/

CREATE OR REPLACE PACKAGE BODY MY_PACKAGE IS
  PROCEDURE process_text(strtab IN OUT string_tabtype) IS
  BEGIN
    NULL;
  END;
END;
/
SHOW ERRORS

DECLARE
  PROCEDURE print(s VARCHAR2) IS
  BEGIN
    DBMS_OUTPUT.PUT_LINE(s);
  END;
BEGIN
  print('Warning settings before: '|| 
         DBMS_WARNING.GET_WARNING_SETTING_STRING);
  compile('my_package');
  print('Warning settings after: '|| 
         DBMS_WARNING.GET_WARNING_SETTING_STRING);
END;
/
SHOW ERRORS PACKAGE MY_PACKAGE
ALTER SESSION SET PLSQL_WARNINGS='DISABLE:ALL';
