CREATE OR REPLACE TRIGGER nodrop
BEFORE DROP ON SCHEMA
BEGIN
  IF DICTIONARY_OBJ_TYPE = 'TABLE' THEN
    RAISE_APPLICATION_ERROR (-20999,
      'Delete of table ' || DICTIONARY_OBJ_NAME ||' not allowed!!');
  END IF;
END;
/
