------------------------------------
-- VENDAS LIQUIDA POR AGRUPAMENTO --
------------------------------------
CREATE OR REPLACE FORCE VIEW BIV100 (
CODIGO,
DATA,
CLIENTE,
FAMILIA,
SUBFAMILIA,
AGRUPAMENTO,
SUBAGRUPAMENTO,
QUANTIDADE,
VALOR,
CUSTO_LIQUIDO,
CUSTO_GGF) 
AS 
(SELECT BI0100.CODIGO,
               BI0100.DATA,
               BI0100.CLIENTE,
               REPLACE(REPLACE(IAT177.COD_FAMILIA,'PT','OU'),'EV','OU') FAMILIA,
               IAT177.COD_SUBFAMILIA SUBFAMILIA,
               BI0100.AGRUPAMENTO,
               BI0100.SUBAGRUPAMENTO,
               BI0100.QUANTIDADE,
               BI0100.VALOR,
               BI0100.CUSTO_LIQUIDO,
               BI0100.CUSTO_GGF
          FROM BI0100, IAT177
         WHERE BI0100.AGRUPAMENTO = IAT177.COD_AGRUPAMENTO
           AND BI0100.SUBAGRUPAMENTO = IAT177.SUB_AGRUPAMENTO
)
WITH READ ONLY;

DROP MATERIALIZED VIEW BIV101;
CREATE MATERIALIZED VIEW "FONTES"."BIV101" 
  TABLESPACE "TB_DADOS_BI"
  BUILD IMMEDIATE
  REFRESH COMPLETE
AS
  SELECT ROWNUM codigo,
    T."DATA",
    T."REPRESENTANTE",
    T."FAMILIA",
    T."SUBFAMILIA",
    T."AGRUPAMENTO",
    T."SUBAGRUPAMENTO",
    T."QUANTIDADE",
    T."VALOR",
    T."CUSTO_LIQUIDO",
    T."CUSTO_GGF"
  FROM
    (SELECT BI0100.DATA,
       TO_NUMBER(CBT055.COD_VENDEDOR, '999') REPRESENTANTE,
       REPLACE(REPLACE(IAT177.COD_FAMILIA,'PT','OU'),'EV','OU') FAMILIA,
       IAT177.COD_SUBFAMILIA SUBFAMILIA,
       BI0100.AGRUPAMENTO,
       BI0100.SUBAGRUPAMENTO,
       SUM(BI0100.QUANTIDADE) QUANTIDADE,
       SUM(BI0100.VALOR) VALOR,
       SUM(BI0100.CUSTO_LIQUIDO) CUSTO_LIQUIDO,
       SUM(BI0100.CUSTO_GGF) CUSTO_GGF
  FROM BI0100, IAT177, FAT017, CBT055
 WHERE BI0100.AGRUPAMENTO = IAT177.COD_AGRUPAMENTO
   AND BI0100.SUBAGRUPAMENTO = IAT177.SUB_AGRUPAMENTO
   AND BI0100.CLIENTE = FAT017.COD_CLIENTE
   AND (FAT017.COD_SETOR = CBT055.COD_VENDEDOR AND CBT055.COD_VENDEDOR <> '090' 
    OR FAT017.COD_SETOR2 = CBT055.COD_VENDEDOR)
GROUP BY BI0100.DATA, 
       CBT055.COD_VENDEDOR, 
       REPLACE(REPLACE(IAT177.COD_FAMILIA,'PT','OU'),'EV','OU'),
       IAT177.COD_SUBFAMILIA,
       BI0100.AGRUPAMENTO, 
       BI0100.SUBAGRUPAMENTO
    ) T;


CREATE OR REPLACE FORCE VIEW BIV102 (
CODIGO,
DATA,
GERENTE,
FAMILIA,
SUBFAMILIA,
AGRUPAMENTO,
SUBAGRUPAMENTO,
QUANTIDADE,
VALOR,
CUSTO_LIQUIDO,
CUSTO_GGF) 
AS 
(SELECT ROWNUM,
        T.*
   FROM (SELECT BI0100.DATA,
                TO_NUMBER(CBT061.COD_GERENCIA, '99') GERENTE,
                REPLACE(REPLACE(IAT177.COD_FAMILIA,'PT','OU'),'EV','OU') FAMILIA,
                IAT177.COD_SUBFAMILIA SUBFAMILIA,
                BI0100.AGRUPAMENTO,
                BI0100.SUBAGRUPAMENTO,
                SUM(BI0100.QUANTIDADE) QUANTIDADE,
                SUM(BI0100.VALOR) VALOR,
                SUM(BI0100.CUSTO_LIQUIDO) CUSTO_LIQUIDO,
                SUM(BI0100.CUSTO_GGF) CUSTO_GGF
           FROM BI0100, IAT177, FAT017, CBT055, CBT061
          WHERE BI0100.AGRUPAMENTO = IAT177.COD_AGRUPAMENTO
            AND BI0100.SUBAGRUPAMENTO = IAT177.SUB_AGRUPAMENTO
            AND BI0100.CLIENTE = FAT017.COD_CLIENTE
            AND (FAT017.COD_SETOR = CBT055.COD_VENDEDOR AND CBT055.COD_VENDEDOR <> '090' 
             OR FAT017.COD_SETOR2 = CBT055.COD_VENDEDOR)
            AND CBT055.COD_GERENCIA = CBT061.COD_GERENCIA
       GROUP BY BI0100.DATA, 
                CBT055.COD_VENDEDOR, 
                CBT061.COD_GERENCIA, 
                REPLACE(REPLACE(IAT177.COD_FAMILIA,'PT','OU'),'EV','OU'),
                IAT177.COD_SUBFAMILIA,
                BI0100.AGRUPAMENTO, 
                BI0100.SUBAGRUPAMENTO) T
)
WITH READ ONLY;


DROP MATERIALIZED VIEW BIV103;
CREATE MATERIALIZED VIEW "FONTES"."BIV103" 
  TABLESPACE "TB_DADOS_BI"
  BUILD IMMEDIATE
  REFRESH COMPLETE
AS
  SELECT ROWNUM codigo,
    T."DATA",
    T."GERENCIA",
    T."FAMILIA",
    T."SUBFAMILIA",
    T."AGRUPAMENTO",
    T."SUBAGRUPAMENTO",
    T."QUANTIDADE",
    T."VALOR",
    T."CUSTO_LIQUIDO",
    T."CUSTO_GGF"
  FROM
    (SELECT BI0100.DATA,
      TO_NUMBER(CBT1431.COD_GER_REGIAO, '99') GERENCIA,
      REPLACE(REPLACE(IAT177.COD_FAMILIA,'PT','OU'),'EV','OU') FAMILIA,
      IAT177.COD_SUBFAMILIA SUBFAMILIA,
      BI0100.AGRUPAMENTO,
      BI0100.SUBAGRUPAMENTO,
      SUM(BI0100.QUANTIDADE) QUANTIDADE,
      SUM(BI0100.VALOR) VALOR,
      SUM(BI0100.CUSTO_LIQUIDO) CUSTO_LIQUIDO,
      SUM(BI0100.CUSTO_GGF) CUSTO_GGF
    FROM BI0100,
      IAT177,
      FAT017,
      CBT055,
      CBT061,
      cbt1431
    WHERE BI0100.AGRUPAMENTO  = IAT177.COD_AGRUPAMENTO
    AND BI0100.SUBAGRUPAMENTO = IAT177.SUB_AGRUPAMENTO
    AND BI0100.CLIENTE        = FAT017.COD_CLIENTE
    AND (FAT017.COD_SETOR     = CBT055.COD_VENDEDOR
    AND CBT055.COD_VENDEDOR  <> '090'
    OR FAT017.COD_SETOR2      = CBT055.COD_VENDEDOR)
    AND CBT055.COD_GERENCIA   = CBT061.COD_GERENCIA
    AND CBT061.COD_GER_REGIAO = CBT1431.COD_GER_REGIAO
    GROUP BY BI0100.DATA,
      CBT1431.COD_GER_REGIAO,
      REPLACE(REPLACE(IAT177.COD_FAMILIA,'PT','OU'),'EV','OU'),
      IAT177.COD_SUBFAMILIA,
      BI0100.AGRUPAMENTO,
      BI0100.SUBAGRUPAMENTO
    ) T;


----------------------------
-- CUTOFF POR AGRUPAMENTO --
----------------------------
CREATE OR REPLACE FORCE VIEW BIV200 (
CODIGO,
DATA,
CLIENTE,
FAMILIA,
SUBFAMILIA,
AGRUPAMENTO,
SUBAGRUPAMENTO,
QUANTIDADE,
VALOR,
CUSTO_LIQUIDO,
CUSTO_GGF) 
AS 
(SELECT ROWNUM,
        T.*
  FROM (SELECT BI0200.DATA,
               BI0200.CLIENTE,
               REPLACE(REPLACE(IAT177.COD_FAMILIA,'PT','OU'),'EV','OU') FAMILIA,
               IAT177.COD_SUBFAMILIA SUBFAMILIA,
               BI0200.AGRUPAMENTO,
               BI0200.SUBAGRUPAMENTO,
               BI0200.QUANTIDADE,
               BI0200.VALOR,
               BI0200.CUSTO_LIQUIDO,
               BI0200.CUSTO_GGF
          FROM BI0200, IAT177
         WHERE BI0200.AGRUPAMENTO = IAT177.COD_AGRUPAMENTO
           AND BI0200.SUBAGRUPAMENTO = IAT177.SUB_AGRUPAMENTO) T
)
WITH READ ONLY;


CREATE OR REPLACE FORCE VIEW BIV201 (
CODIGO,
DATA,
REPRESENTANTE,
FAMILIA,
SUBFAMILIA,
AGRUPAMENTO,
SUBAGRUPAMENTO,
QUANTIDADE,
VALOR,
CUSTO_LIQUIDO,
CUSTO_GGF) 
AS 
(SELECT ROWNUM,
        T.*
  FROM (SELECT BI0200.DATA,
               TO_NUMBER(CBT055.COD_VENDEDOR, '999') REPRESENTANTE,
               REPLACE(REPLACE(IAT177.COD_FAMILIA,'PT','OU'),'EV','OU') FAMILIA,
               IAT177.COD_SUBFAMILIA SUBFAMILIA,
               BI0200.AGRUPAMENTO,
               BI0200.SUBAGRUPAMENTO,
               SUM(BI0200.QUANTIDADE) QUANTIDADE,
               SUM(BI0200.VALOR) VALOR,
               SUM(BI0200.CUSTO_LIQUIDO) CUSTO_LIQUIDO,
               SUM(BI0200.CUSTO_GGF) CUSTO_GGF
          FROM BI0200, IAT177, FAT017, CBT055
         WHERE BI0200.AGRUPAMENTO = IAT177.COD_AGRUPAMENTO
           AND BI0200.SUBAGRUPAMENTO = IAT177.SUB_AGRUPAMENTO
           AND BI0200.CLIENTE = FAT017.COD_CLIENTE
           AND (FAT017.COD_SETOR = CBT055.COD_VENDEDOR AND CBT055.COD_VENDEDOR <> '090' 
            OR FAT017.COD_SETOR2 = CBT055.COD_VENDEDOR)
      GROUP BY BI0200.DATA, 
               CBT055.COD_VENDEDOR, 
               REPLACE(REPLACE(IAT177.COD_FAMILIA,'PT','OU'),'EV','OU'),
               IAT177.COD_SUBFAMILIA,
               BI0200.AGRUPAMENTO, 
               BI0200.SUBAGRUPAMENTO) T
)
WITH READ ONLY;


CREATE OR REPLACE FORCE VIEW BIV202 (
CODIGO,
DATA,
GERENTE,
FAMILIA,
SUBFAMILIA,
AGRUPAMENTO,
SUBAGRUPAMENTO,
QUANTIDADE,
VALOR,
CUSTO_LIQUIDO,
CUSTO_GGF) 
AS 
(SELECT ROWNUM,
        T.*
   FROM (SELECT BI0200.DATA,
                TO_NUMBER(CBT061.COD_GERENCIA, '99') GERENTE,
                REPLACE(REPLACE(IAT177.COD_FAMILIA,'PT','OU'),'EV','OU') FAMILIA,
                IAT177.COD_SUBFAMILIA SUBFAMILIA,
                BI0200.AGRUPAMENTO,
                BI0200.SUBAGRUPAMENTO,
                SUM(BI0200.QUANTIDADE) QUANTIDADE,
                SUM(BI0200.VALOR) VALOR,
                SUM(BI0200.CUSTO_LIQUIDO) CUSTO_LIQUIDO,
                SUM(BI0200.CUSTO_GGF) CUSTO_GGF
           FROM BI0200, IAT177, FAT017, CBT055, CBT061
          WHERE BI0200.AGRUPAMENTO = IAT177.COD_AGRUPAMENTO
            AND BI0200.SUBAGRUPAMENTO = IAT177.SUB_AGRUPAMENTO
            AND BI0200.CLIENTE = FAT017.COD_CLIENTE
            AND (FAT017.COD_SETOR = CBT055.COD_VENDEDOR AND CBT055.COD_VENDEDOR <> '090' 
             OR FAT017.COD_SETOR2 = CBT055.COD_VENDEDOR)
            AND CBT055.COD_GERENCIA = CBT061.COD_GERENCIA
       GROUP BY BI0200.DATA, 
                CBT055.COD_VENDEDOR, 
                CBT061.COD_GERENCIA, 
                REPLACE(REPLACE(IAT177.COD_FAMILIA,'PT','OU'),'EV','OU'),
                IAT177.COD_SUBFAMILIA,
                BI0200.AGRUPAMENTO, 
                BI0200.SUBAGRUPAMENTO) T
)
WITH READ ONLY;


CREATE OR REPLACE FORCE VIEW BIV203 (
CODIGO,
DATA,
GERENCIA,
FAMILIA,
SUBFAMILIA,
AGRUPAMENTO,
SUBAGRUPAMENTO,
QUANTIDADE,
VALOR,
CUSTO_LIQUIDO,
CUSTO_GGF) 
AS 
(SELECT ROWNUM,
        T.*
  FROM (SELECT BI0200.DATA,
               TO_NUMBER(CBT1431.COD_GER_REGIAO, '99') GERENCIA,
               REPLACE(REPLACE(IAT177.COD_FAMILIA,'PT','OU'),'EV','OU') FAMILIA,
               IAT177.COD_SUBFAMILIA SUBFAMILIA,
               BI0200.AGRUPAMENTO,
               BI0200.SUBAGRUPAMENTO,
               SUM(BI0200.QUANTIDADE) QUANTIDADE,
               SUM(BI0200.VALOR) VALOR,
               SUM(BI0200.CUSTO_LIQUIDO) CUSTO_LIQUIDO,
               SUM(BI0200.CUSTO_GGF) CUSTO_GGF
          FROM BI0200, IAT177, FAT017, CBT055, CBT061, cbt1431
         WHERE BI0200.AGRUPAMENTO = IAT177.COD_AGRUPAMENTO
           AND BI0200.SUBAGRUPAMENTO = IAT177.SUB_AGRUPAMENTO
           AND BI0200.CLIENTE = FAT017.COD_CLIENTE
           AND (FAT017.COD_SETOR = CBT055.COD_VENDEDOR AND CBT055.COD_VENDEDOR <> '090' 
            OR FAT017.COD_SETOR2 = CBT055.COD_VENDEDOR)
           AND CBT055.COD_GERENCIA = CBT061.COD_GERENCIA
           AND CBT061.COD_GER_REGIAO = CBT1431.COD_GER_REGIAO
      GROUP BY BI0200.DATA, 
               CBT1431.COD_GER_REGIAO, 
               REPLACE(REPLACE(IAT177.COD_FAMILIA,'PT','OU'),'EV','OU'),
               IAT177.COD_SUBFAMILIA,
               BI0200.AGRUPAMENTO, 
               BI0200.SUBAGRUPAMENTO) T
)
WITH READ ONLY;


--------------------------------
-- VENDAS LIQUIDA POR PRODUTO --
--------------------------------
CREATE OR REPLACE FORCE VIEW BIV110 (
CODIGO,
DATA,
CLIENTE,
PRODUTO_GRUPO,
PRODUTO_SUBGRUPO,
PRODUTO_NUMERO,
PRODUTO_UNIDADE,
FAMILIA,
SUBFAMILIA,
QUANTIDADE,
VALOR,
CUSTO_LIQUIDO,
CUSTO_GGF) 
AS 
(SELECT BI0110.CODIGO,
            BI0110.DATA,
            BI0110.CLIENTE,
            BI0110.PRODUTO_GRUPO,
            BI0110.PRODUTO_SUBGRUPO,
            BI0110.PRODUTO_NUMERO,
            BI0110.PRODUTO_UNIDADE,
            IAT177.COD_FAMILIA,
            IAT177.COD_SUBFAMILIA,
            SUM(BI0110.QUANTIDADE) QUANTIDADE,
            SUM(BI0110.VALOR) VALOR,
            SUM(BI0110.CUSTO_LIQUIDO) CUSTO_LIQUIDO,
            SUM(BI0110.CUSTO_GGF) CUSTO_GGF
       FROM BI0110, IAT037, IAT177
      WHERE BI0110.PRODUTO_GRUPO = IAT037.COD_GRUPO(+)
          AND BI0110.PRODUTO_SUBGRUPO = IAT037.COD_SUBGRUPO(+)
          AND BI0110.PRODUTO_NUMERO = IAT037.NUM_PRODUTO(+)
          AND BI0110.PRODUTO_UNIDADE = IAT037.COD_UNIDADE(+)
        AND IAT037.COD_AGRUPAMENTO = IAT177.COD_AGRUPAMENTO(+)
        AND IAT037.SUB_AGRUPAMENTO = IAT177.SUB_AGRUPAMENTO(+)
   GROUP BY BI0110.CODIGO,
            BI0110.DATA, 
            BI0110.CLIENTE,
            BI0110.PRODUTO_GRUPO,
            BI0110.PRODUTO_SUBGRUPO,
            BI0110.PRODUTO_NUMERO,
            BI0110.PRODUTO_UNIDADE,
            IAT177.COD_FAMILIA,
            IAT177.COD_SUBFAMILIA
)
WITH READ ONLY;


CREATE OR REPLACE FORCE VIEW BIV111 (
CODIGO,
DATA,
REPRESENTANTE,
PRODUTO_GRUPO,
PRODUTO_SUBGRUPO,
PRODUTO_NUMERO,
PRODUTO_UNIDADE,
FAMILIA,
SUBFAMILIA,
QUANTIDADE,
VALOR,
CUSTO_LIQUIDO,
CUSTO_GGF) 
AS 
(SELECT BI0110.CODIGO,
            BI0110.DATA,
            TO_NUMBER(CBT055.COD_VENDEDOR, '999') REPRESENTANTE,
            BI0110.PRODUTO_GRUPO,
            BI0110.PRODUTO_SUBGRUPO,
            BI0110.PRODUTO_NUMERO,
            BI0110.PRODUTO_UNIDADE,
            IAT177.COD_FAMILIA,
            IAT177.COD_SUBFAMILIA,
            SUM(BI0110.QUANTIDADE) QUANTIDADE,
            SUM(BI0110.VALOR) VALOR,
            SUM(BI0110.CUSTO_LIQUIDO) CUSTO_LIQUIDO,
            SUM(BI0110.CUSTO_GGF) CUSTO_GGF
       FROM BI0110, FAT017, CBT055, IAT037, IAT177
      WHERE BI0110.CLIENTE = FAT017.COD_CLIENTE
          AND BI0110.PRODUTO_GRUPO = IAT037.COD_GRUPO(+)
          AND BI0110.PRODUTO_SUBGRUPO = IAT037.COD_SUBGRUPO(+)
          AND BI0110.PRODUTO_NUMERO = IAT037.NUM_PRODUTO(+)
          AND BI0110.PRODUTO_UNIDADE = IAT037.COD_UNIDADE(+)
        AND IAT037.COD_AGRUPAMENTO = IAT177.COD_AGRUPAMENTO(+)
        AND IAT037.SUB_AGRUPAMENTO = IAT177.SUB_AGRUPAMENTO(+)
          AND (FAT017.COD_SETOR = CBT055.COD_VENDEDOR AND CBT055.COD_VENDEDOR <> '090' 
           OR FAT017.COD_SETOR2 = CBT055.COD_VENDEDOR)
   GROUP BY BI0110.CODIGO,
            BI0110.DATA, 
            CBT055.COD_VENDEDOR,
            BI0110.PRODUTO_GRUPO,
            BI0110.PRODUTO_SUBGRUPO,
            BI0110.PRODUTO_NUMERO,
            BI0110.PRODUTO_UNIDADE,
            IAT177.COD_FAMILIA,
            IAT177.COD_SUBFAMILIA
)
WITH READ ONLY;


CREATE OR REPLACE FORCE VIEW BIV112 (
CODIGO,
DATA,
GERENTE,
PRODUTO_GRUPO,
PRODUTO_SUBGRUPO,
PRODUTO_NUMERO,
PRODUTO_UNIDADE,
FAMILIA,
SUBFAMILIA,
QUANTIDADE,
VALOR,
CUSTO_LIQUIDO,
CUSTO_GGF) 
AS 
(SELECT BI0110.CODIGO,
            BI0110.DATA,
            TO_NUMBER(CBT061.COD_GERENCIA, '99') GERENTE,
            BI0110.PRODUTO_GRUPO,
            BI0110.PRODUTO_SUBGRUPO,
            BI0110.PRODUTO_NUMERO,
            BI0110.PRODUTO_UNIDADE,
            IAT177.COD_FAMILIA,
            IAT177.COD_SUBFAMILIA,
            SUM(BI0110.QUANTIDADE) QUANTIDADE,
            SUM(BI0110.VALOR) VALOR,
            SUM(BI0110.CUSTO_LIQUIDO) CUSTO_LIQUIDO,
            SUM(BI0110.CUSTO_GGF) CUSTO_GGF
       FROM BI0110, FAT017, CBT055, CBT061, IAT037, IAT177
      WHERE BI0110.CLIENTE = FAT017.COD_CLIENTE
        AND (FAT017.COD_SETOR = CBT055.COD_VENDEDOR AND CBT055.COD_VENDEDOR <> '090' 
         OR FAT017.COD_SETOR2 = CBT055.COD_VENDEDOR)
        AND CBT055.COD_GERENCIA = CBT061.COD_GERENCIA
          AND BI0110.PRODUTO_GRUPO = IAT037.COD_GRUPO(+)
          AND BI0110.PRODUTO_SUBGRUPO = IAT037.COD_SUBGRUPO(+)
          AND BI0110.PRODUTO_NUMERO = IAT037.NUM_PRODUTO(+)
          AND BI0110.PRODUTO_UNIDADE = IAT037.COD_UNIDADE(+)
        AND IAT037.COD_AGRUPAMENTO = IAT177.COD_AGRUPAMENTO(+)
        AND IAT037.SUB_AGRUPAMENTO = IAT177.SUB_AGRUPAMENTO(+)
   GROUP BY BI0110.CODIGO,
            BI0110.DATA, 
            CBT061.COD_GERENCIA, 
            BI0110.PRODUTO_GRUPO,
            BI0110.PRODUTO_SUBGRUPO,
            BI0110.PRODUTO_NUMERO,
            BI0110.PRODUTO_UNIDADE,
            IAT177.COD_FAMILIA,
            IAT177.COD_SUBFAMILIA
)
WITH READ ONLY;

CREATE OR REPLACE FORCE VIEW BIV113 (
CODIGO,
DATA,
GERENCIA,
PRODUTO_GRUPO,
PRODUTO_SUBGRUPO,
PRODUTO_NUMERO,
PRODUTO_UNIDADE,
FAMILIA,
SUBFAMILIA,
QUANTIDADE,
VALOR,
CUSTO_LIQUIDO,
CUSTO_GGF) 
AS 
(SELECT BI0110.CODIGO,
            BI0110.DATA,
            TO_NUMBER(CBT1431.COD_GER_REGIAO, '99') GERENCIA,
            BI0110.PRODUTO_GRUPO,
            BI0110.PRODUTO_SUBGRUPO,
            BI0110.PRODUTO_NUMERO,
            BI0110.PRODUTO_UNIDADE,
            IAT177.COD_FAMILIA,
            IAT177.COD_SUBFAMILIA,
            SUM(BI0110.QUANTIDADE) QUANTIDADE,
            SUM(BI0110.VALOR) VALOR,
            SUM(BI0110.CUSTO_LIQUIDO) CUSTO_LIQUIDO,
            SUM(BI0110.CUSTO_GGF) CUSTO_GGF
       FROM BI0110, FAT017, CBT055, CBT061, CBT1431, IAT037, IAT177
      WHERE BI0110.CLIENTE = FAT017.COD_CLIENTE
        AND (FAT017.COD_SETOR = CBT055.COD_VENDEDOR AND CBT055.COD_VENDEDOR <> '090' 
         OR FAT017.COD_SETOR2 = CBT055.COD_VENDEDOR)
        AND CBT055.COD_GERENCIA = CBT061.COD_GERENCIA
        AND CBT061.COD_GER_REGIAO = CBT1431.COD_GER_REGIAO
          AND BI0110.PRODUTO_GRUPO = IAT037.COD_GRUPO(+)
          AND BI0110.PRODUTO_SUBGRUPO = IAT037.COD_SUBGRUPO(+)
          AND BI0110.PRODUTO_NUMERO = IAT037.NUM_PRODUTO(+)
          AND BI0110.PRODUTO_UNIDADE = IAT037.COD_UNIDADE(+)
        AND IAT037.COD_AGRUPAMENTO = IAT177.COD_AGRUPAMENTO(+)
        AND IAT037.SUB_AGRUPAMENTO = IAT177.SUB_AGRUPAMENTO(+)
   GROUP BY BI0110.CODIGO,
            BI0110.DATA, 
            CBT1431.COD_GER_REGIAO,
            BI0110.PRODUTO_GRUPO,
            BI0110.PRODUTO_SUBGRUPO,
            BI0110.PRODUTO_NUMERO,
            BI0110.PRODUTO_UNIDADE,
            IAT177.COD_FAMILIA,
            IAT177.COD_SUBFAMILIA
)
WITH READ ONLY;


------------------------
-- CUTOFF POR PRODUTO --
------------------------
CREATE OR REPLACE FORCE VIEW BIV211 (
CODIGO,
DATA,
REPRESENTANTE,
PRODUTO_GRUPO,
PRODUTO_SUBGRUPO,
PRODUTO_NUMERO,
PRODUTO_UNIDADE,
FAMILIA,
SUBFAMILIA,
QUANTIDADE,
VALOR,
CUSTO_LIQUIDO,
CUSTO_GGF) 
AS 
(SELECT BI0210.CODIGO,
            BI0210.DATA,
            TO_NUMBER(CBT055.COD_VENDEDOR, '999') REPRESENTANTE,
            BI0210.PRODUTO_GRUPO,
            BI0210.PRODUTO_SUBGRUPO,
            BI0210.PRODUTO_NUMERO,
            BI0210.PRODUTO_UNIDADE,
            IAT177.COD_FAMILIA,
            IAT177.COD_SUBFAMILIA,
            SUM(BI0210.QUANTIDADE) QUANTIDADE,
            SUM(BI0210.VALOR) VALOR,
            SUM(BI0210.CUSTO_LIQUIDO) CUSTO_LIQUIDO,
            SUM(BI0210.CUSTO_GGF) CUSTO_GGF
       FROM BI0210, FAT017, CBT055, IAT037, IAT177
      WHERE BI0210.CLIENTE = FAT017.COD_CLIENTE
        AND (FAT017.COD_SETOR = CBT055.COD_VENDEDOR AND CBT055.COD_VENDEDOR <> '090' 
            OR FAT017.COD_SETOR2 = CBT055.COD_VENDEDOR)
          AND BI0210.PRODUTO_GRUPO = IAT037.COD_GRUPO(+)
          AND BI0210.PRODUTO_SUBGRUPO = IAT037.COD_SUBGRUPO(+)
          AND BI0210.PRODUTO_NUMERO = IAT037.NUM_PRODUTO(+)
          AND BI0210.PRODUTO_UNIDADE = IAT037.COD_UNIDADE(+)
        AND IAT037.COD_AGRUPAMENTO = IAT177.COD_AGRUPAMENTO(+)
        AND IAT037.SUB_AGRUPAMENTO = IAT177.SUB_AGRUPAMENTO(+)
   GROUP BY BI0210.CODIGO,
            BI0210.DATA, 
            CBT055.COD_VENDEDOR,
            BI0210.PRODUTO_GRUPO,
            BI0210.PRODUTO_SUBGRUPO,
            BI0210.PRODUTO_NUMERO,
            BI0210.PRODUTO_UNIDADE,
            IAT177.COD_FAMILIA,
            IAT177.COD_SUBFAMILIA
)
WITH READ ONLY;


CREATE OR REPLACE FORCE VIEW BIV212 (
CODIGO,
DATA,
GERENTE,
PRODUTO_GRUPO,
PRODUTO_SUBGRUPO,
PRODUTO_NUMERO,
PRODUTO_UNIDADE,
FAMILIA,
SUBFAMILIA,
QUANTIDADE,
VALOR,
CUSTO_LIQUIDO,
CUSTO_GGF) 
AS 
(SELECT BI0210.CODIGO,
            BI0210.DATA,
            TO_NUMBER(CBT061.COD_GERENCIA, '99') GERENTE,
            BI0210.PRODUTO_GRUPO,
            BI0210.PRODUTO_SUBGRUPO,
            BI0210.PRODUTO_NUMERO,
            BI0210.PRODUTO_UNIDADE,
            IAT177.COD_FAMILIA,
            IAT177.COD_SUBFAMILIA,
            SUM(BI0210.QUANTIDADE) QUANTIDADE,
            SUM(BI0210.VALOR) VALOR,
            SUM(BI0210.CUSTO_LIQUIDO) CUSTO_LIQUIDO,
            SUM(BI0210.CUSTO_GGF) CUSTO_GGF
       FROM BI0210, FAT017, CBT055, CBT061, IAT037, IAT177
      WHERE BI0210.CLIENTE = FAT017.COD_CLIENTE
        AND (FAT017.COD_SETOR = CBT055.COD_VENDEDOR AND CBT055.COD_VENDEDOR <> '090' 
         OR FAT017.COD_SETOR2 = CBT055.COD_VENDEDOR)
        AND CBT055.COD_GERENCIA = CBT061.COD_GERENCIA
          AND BI0210.PRODUTO_GRUPO = IAT037.COD_GRUPO(+)
          AND BI0210.PRODUTO_SUBGRUPO = IAT037.COD_SUBGRUPO(+)
          AND BI0210.PRODUTO_NUMERO = IAT037.NUM_PRODUTO(+)
          AND BI0210.PRODUTO_UNIDADE = IAT037.COD_UNIDADE(+)
        AND IAT037.COD_AGRUPAMENTO = IAT177.COD_AGRUPAMENTO(+)
        AND IAT037.SUB_AGRUPAMENTO = IAT177.SUB_AGRUPAMENTO(+)
   GROUP BY BI0210.CODIGO,
            BI0210.DATA, 
            CBT061.COD_GERENCIA, 
            BI0210.PRODUTO_GRUPO,
            BI0210.PRODUTO_SUBGRUPO,
            BI0210.PRODUTO_NUMERO,
            BI0210.PRODUTO_UNIDADE,
            IAT177.COD_FAMILIA,
            IAT177.COD_SUBFAMILIA
)
WITH READ ONLY;

CREATE OR REPLACE FORCE VIEW BIV213 (
CODIGO,
DATA,
GERENCIA,
PRODUTO_GRUPO,
PRODUTO_SUBGRUPO,
PRODUTO_NUMERO,
PRODUTO_UNIDADE,
FAMILIA,
SUBFAMILIA,
QUANTIDADE,
VALOR,
CUSTO_LIQUIDO,
CUSTO_GGF) 
AS 
(SELECT BI0210.CODIGO,
            BI0210.DATA,
            TO_NUMBER(CBT1431.COD_GER_REGIAO, '99') GERENCIA,
            BI0210.PRODUTO_GRUPO,
            BI0210.PRODUTO_SUBGRUPO,
            BI0210.PRODUTO_NUMERO,
            BI0210.PRODUTO_UNIDADE,
            IAT177.COD_FAMILIA,
            IAT177.COD_SUBFAMILIA,
            SUM(BI0210.QUANTIDADE) QUANTIDADE,
            SUM(BI0210.VALOR) VALOR,
            SUM(BI0210.CUSTO_LIQUIDO) CUSTO_LIQUIDO,
            SUM(BI0210.CUSTO_GGF) CUSTO_GGF
       FROM BI0210, FAT017, CBT055, CBT061, CBT1431, IAT037, IAT177
      WHERE BI0210.CLIENTE = FAT017.COD_CLIENTE
        AND (FAT017.COD_SETOR = CBT055.COD_VENDEDOR AND CBT055.COD_VENDEDOR <> '090' 
         OR FAT017.COD_SETOR2 = CBT055.COD_VENDEDOR)
        AND CBT055.COD_GERENCIA = CBT061.COD_GERENCIA
        AND CBT061.COD_GER_REGIAO = CBT1431.COD_GER_REGIAO
          AND BI0210.PRODUTO_GRUPO = IAT037.COD_GRUPO(+)
          AND BI0210.PRODUTO_SUBGRUPO = IAT037.COD_SUBGRUPO(+)
          AND BI0210.PRODUTO_NUMERO = IAT037.NUM_PRODUTO(+)
          AND BI0210.PRODUTO_UNIDADE = IAT037.COD_UNIDADE(+)
        AND IAT037.COD_AGRUPAMENTO = IAT177.COD_AGRUPAMENTO(+)
        AND IAT037.SUB_AGRUPAMENTO = IAT177.SUB_AGRUPAMENTO(+)
   GROUP BY BI0210.CODIGO,
            BI0210.DATA, 
            CBT1431.COD_GER_REGIAO,
            BI0210.PRODUTO_GRUPO,
            BI0210.PRODUTO_SUBGRUPO,
            BI0210.PRODUTO_NUMERO,
            BI0210.PRODUTO_UNIDADE,
            IAT177.COD_FAMILIA,
            IAT177.COD_SUBFAMILIA
)
WITH READ ONLY;

